In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a*a

array([1, 4, 9])

In [3]:
np.dot(a,a)

14

In [4]:
a[:,None].shape

(3, 1)

In [5]:
a[:,axis=1]

SyntaxError: invalid syntax (<ipython-input-5-c25af7e8a341>, line 1)

In [6]:
a

array([1, 2, 3])

In [7]:
b= np.array([
    [1,1,1],
    [2,2,2]
])
b.shape

(2, 3)

In [8]:
a*b

array([[1, 2, 3],
       [2, 4, 6]])

In [9]:
a.shape

(3,)

In [13]:

c = np.array([[0.5, -0.2, 0.1]])
d = np.array([[0.1, -0.2],
                       [0.4, 0.5],
                       [-0.3, 0.2]])
c*d

ValueError: operands could not be broadcast together with shapes (1,3) (3,2) 

In [14]:
np.dot(c,d)

array([[-0.06, -0.18]])

In [15]:
np.dot(d,c)

ValueError: shapes (3,2) and (1,3) not aligned: 2 (dim 1) != 1 (dim 0)